---
- name: Configure OPS445 CentOS VM
  hosts: vmlab
  user: student
  become: yes
  vars:
    seneca_id: aholder5
    ssh_pub_key: "{{ lookup('file', '/home/aholder5/.ssh/id_ed25519.pub') }}"
  tasks:

    - name: Ensure Apache is the latest version
      yum:
        name: httpd
        state: latest

    - name: Ensure epel-release is installed
      yum:
        name: epel-release
        state: present

    - name: Remove the 'tree' package
      yum:
        name: tree
        state: absent

    - name: Set hostname to Seneca ID
      hostname:
        name: "{{ seneca_id }}"

    - name: Create user with Seneca ID
      user:
        name: "{{ seneca_id }}"
        shell: /bin/bash
        groups: wheel
        append: yes
        state: present
        create_home: yes

    - name: Allow SSH key-based login for new user
      authorized_key:
        user: "{{ seneca_id }}"
        state: present
        key: "{{ ssh_pub_key }}"

    - name: Create lab directories under ~/ops445
      file:
        path: "/home/{{ seneca_id }}/ops445/lab{{ item }}"
        state: directory
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: '0755'
      loop: "{{ range(1, 9) | list }}"

